---
- name: "Login no ECR e implantação do container"
  hosts: all
  become: true
  vars:
    aws_access_key: "{{ AWS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    aws_region: "us-east-2"
    image_name: "discord-bot:release"
    container_name: "discord-bot"
    ecr_url: "271439737792.dkr.ecr.us-east-2.amazonaws.com"

  tasks:
    - name: Fazer login no Amazon ECR
      become: yes
      docker_login:
        username: pipeline
        password: "{{ aws_secret_key }}"
        registry_url: "{{ ecr_url }}"
    
    - name: "Implantar o container"
      docker_container:
        name: "{{ container_name }}"
        image: "{{ ecr_url }}/{{ image_name }}"
        pull: yes
        state: started
        restart_policy: unless-stopped
        recreate: yes
        state: started
