---
- name: "Login no ECR e implantação do container"
  hosts: vitorlivi.online
  become: true
  vars:
    aws_access_key: "{{ AWS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    aws_region: "us-east-2"
    image_name: "seu_ecr_image"
    container_name: "discord-bot"
    ecr_url: "271439737792.dkr.ecr.us-east-2.amazonaws.com"

  tasks:
    - name: "Logar no ECR"
      community.aws.ecr_login:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"

    - name: "Fazer pull da imagem do ECR"
      docker_image:
        name: "{{ ecr_url }}/{{ image_name }}"
        source: pull

    - name: "Implantar o container"
      docker_container:
        name: "{{ container_name }}"
        image: "{{ ecr_url }}/{{ image_name }}"
        pull: yes
        state: started
        restart_policy: unless-stopped
        recreate: yes
        state: started