on:
  push:
    branches:
      - main

name: Production CI/CD

jobs:
  deploy:
    name: Run playbook
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy container
        uses: dawidd6/action-ansible-playbook@v2
        env:
          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
        with:
          playbook: deploy.yml
          directory: configs/deploy
          inventory: |
            [all]
            ssh.vitorlivi.online ansible_ssh_host=ssh.vitorlivi.online ansible_connection=ssh ansible_ssh_user={{ secrets.SSH_USER }} ansible_ssh_pass={{ secrets.SSH_PASS }}
